# Generated by Django 2.2.16 on 2022-09-21 18:15

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20220921_2114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='no_self_rating',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='subscribe_to_yourself'),
        ),
    ]
